### PR TITLE
GETEM cost model, well count updates

### LINKED ISSUE #1247: GETEM gross power output not updating for full calculations
**Describe the bug**
-GETEM gross plant size not updating in lib_geothermal.cpp when cmod_geothermal.cpp is run with ui_calculations_only is set to 0. Add the call to update the gross plant size pointer not just when the interface needs to be updated.

### PR DESCRIPTION
**Pull request by mjprilliman**
-Update cost calculations
-Update well count calculations
-Move capex costs from GUI equations to cmod_geothermal_costs
-Closes #1247

### CODE REVIEW

File: ssc/cmod_geothermal_costs_eqns.h [hunk 1]
```diff
@@ -40,16 +40,26 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 extern "C" {
 #endif
 
-static const char* getem_om_cost_calc_doc =
-    "Calculates the cable length in an ME array\\n"
+static const char* getem_om_cost_calc_doc =    
+    "Calculate annual O&M costs for geothermal power plants \\n\\n"
```
Comment (sjanzou) [inline ssc/cmod_geothermal_costs_eqns.h:44]: definitely more descriptive!

**Review by sjanzou — APPROVED** [review]
Everything running fine. Thanks for enduring this!
