### PR TITLE
Fix a bug flagged by the warning: left operand of comma operator has no effect

### LINKED ISSUE #35: bug in Heliostat::getPanelById
As far as I can see, this function has never worked properly. g++ warns about this problem with the following messages:

../solarpilot/Heliostat.cpp:748:18: warning: left operand of comma operator has no effect [-Wunused-value]
../solarpilot/Heliostat.cpp:749:23: warning: left operand of comma operator has no effect [-Wunused-value]
../solarpilot/Heliostat.cpp:756:20: warning: left operand of comma operator has no effect [-Wunused-value]
../solarpilot/Heliostat.cpp:764:23: warning: left operand of comma operator has no effect [-Wunused-value]

I think this is a genuine bug, so submitting this issue (and I'll also submit a PR that fixes it).

### PR DESCRIPTION
**Pull request by bje-**
Fixes #35. 

* solarpilot/Heliostat.cpp (getPanelById): matrix_t::operator[] only
  takes a single int and returns the address of the row. Instead, use
  the public at() method to properly access matrix elements by row
  and column number.

### CODE REVIEW

**Comment by jdpipe** [comment]
well spotted, ben!

File: solarpilot/Heliostat.cpp [hunk 1]
```diff
@@ -745,23 +745,22 @@ Reflector *Heliostat::getPanelById(int id){
 
 	for (int j=0; j<(int)ncantx; j++) {
 		for (int i=0; i<(int)ncanty; i++) {
-			if (_panels[j,i].getId() == id){
-				return &_panels[j,i];
```
Comment (nickdiorio) [inline solarpilot/Heliostat.cpp]: Seems like a fairly insidious bug, from the perspective that an operator [] with two operands is not defined for a matrix_t, and so only the right operand gets evaluated according to https://stackoverflow.com/questions/54142/how-does-the-comma-operator-work .

Comment (nickdiorio) [reply solarpilot/Heliostat.cpp]: I agree, nice find!
