### PR TITLE
Copy values to a new vector that should solve snow model re-initaliza…

### LINKED ISSUE #1372: Intermittent test failure on Windows for CMPvsamv1PowerIntegration_cmod_pvsamv1.UserArraySnowModel
[ RUN      ] CMPvsamv1PowerIntegration_cmod_pvsamv1.UserArraySnowModel
error during simulation.exec fail(pvsamv1): The weather file contains no snow depth data or the data is not valid. Found (500) bad snow depth values.
D:\a\ssc\ssc\ssc\test\ssc_test\cmod_pvsamv1_test.cpp(1102): error: Value of: pvsam_errors
  Actual: true
Expected: false
D:\a\ssc\ssc\ssc\test\ssc_test\cmod_pvsamv1_test.cpp(1118): error: The difference between annual_energy and 10663 is 192.31966924917288, which exceeds m_error_tolerance_hi, where
annual_energy evaluates to 10855.319669249173,
10663 evaluates to 10663, and
m_error_tolerance_hi evaluates to 1.
Annual energy.
Only occurs on Windows runner, passes on others. Figure out why this would vary by platform and correct accordingly.

### PR DESCRIPTION
**Pull request by brtietz**
…tion errors

### Description

Attempt at solving https://github.com/NatLabRockies/ssc/issues/1372

Hypothesis is that keeping a pointer for the snow data array and passing that to multiple tests caused the memory to be corrupted and the results to change. Copy these values into a vector so the underlying data doesn't change run to run.

Credit to Claude Sonnet for spotting the memory re-use. Blame to Claude Sonnet for some of the annoying tab/spacing changes on the close braces.

Fixes https://github.com/NatLabRockies/ssc/issues/1372

### Corresponding branches and PRs:

Develop on all other branches

### Unit Test Impact:

Expect tests to pass consistently across OSes

### Checklist
- [ ] requires help revision and I added that label
- [ ] adds, removes, modifies, or deletes variables in existing compute modules
- [ ] adds a new compute module
- [ ] changes defaults
- [ ] I've tagged this PR to a milestone

### Reminders- this section can be deleted
[Checking for PySAM Incompatible API Changes]
(https://github.com/NREL/SAM/wiki/PySAM-Incompatible-API-Changes-&-Regenerating-PySAM-Files).

[When do the PySAM files need to be regenerated?]
(https://github.com/NREL/SAM/wiki/PySAM-Incompatible-API-Changes-&-Regenerating-PySAM-Files#when-do-the-pysam-files-need-to-be-regenerated-via-export_config)

### CODE REVIEW

File: test/ssc_test/cmod_pvsamv1_test.cpp [hunk 1]
```diff
@@ -1173,7 +1177,7 @@ TEST_F(CMPvsamv1PowerIntegration_cmod_pvsamv1, SubhourlyClippingCorrectionModel)
         for (int j = 0; j < 17; j++) {
             Subhourly_Clipping_Matrix_Short[i * 17 + j] = Subhourly_Clipping_Matrix[i * 21 + j];
         }
-    }
+        }
```
Comment (sjanzou) [inline test/ssc_test/cmod_pvsamv1_test.cpp:1180]: Some of these spacings seem off - no code impact, just readability

File: test/ssc_test/cmod_pvsamv1_test.cpp [hunk 2]
```diff
@@ -1081,7 +1081,11 @@ TEST_F(CMPvsamv1PowerIntegration_cmod_pvsamv1, UserArraySnowModel)
     // pull the wf snow data and put it into an array
     int l = 8760;
     ssc_number_t* snowdepth = ssc_data_get_array(data, "snowdepth", &l);
-    ssc_data_set_array(data, "snow_array", snowdepth, 8760);
+    // Copy into a local vector immediately: the raw pointer points into var_table
```
Comment (sjanzou) [inline test/ssc_test/cmod_pvsamv1_test.cpp:1084]: Awesome update! Thanks for digging into this - I am testing on a different branch to confirm the intermittently failing test is passing.

**Review by sjanzou — APPROVED** [review]
Great update and running locally and fixed failed GitHub runners on particle_gen3_csp branch of ssc!
