### PR TITLE
Remove extraneous i==1 from cashloan. Also correct typo in comments to issue number (1038)

### LINKED ISSUE #939: ITC payments after year 1 are not computed in cashloan
**Describe the bug**
Testing ITC payments across multiple years works in Single Owner, but Cash loan only applies the payment in the first year:

image

**To Reproduce**
1. Create a PVWatts-Residential Case
2. Specify an ITC payment across mutliple years
3. Run the simulation and go to the cash flow tab
4. See the ITC payments in years 2 - n being ignored

**Expected behavior**
ITC should effect cash flow in out years

**Desktop (please complete the following information):**
 - Version 2022.11.21 rc2

### PR DESCRIPTION
**Pull request by brtietz**
Fixes #939 The fix for that is in cashloan line 1043. Test file is here, shows correct implementation of depreciation adjustments: 
[cashloan_itc_test.zip](https://github.com/NREL/ssc/files/10034373/cashloan_itc_test.zip)

I audited the other code for similar issues and didn't find any. Additional testing never hurts.

All other changes update the issue number to match https://github.com/NREL/SAM/issues/1038, so future developers aren't looking at the wrong issue.

### CODE REVIEW

**Review by cpaulgilman — APPROVED** [review]
Looks good to me. This will get more robust testing for all financial models when I address send-to-Excel with equations for Patch 1: https://github.com/NREL/SAM/issues/1259

File: ssc/cmod_cashloan.cpp [hunk 1]
```diff
@@ -767,14 +767,14 @@ class cm_cashloan : public compute_module
 			- ( as_boolean("cbi_oth_deprbas_sta")  ? cbi_oth_amount : 0 );
 
 
-        // SAM 1308
+        // SAM 1038
```
Comment (sjanzou) [inline ssc/cmod_cashloan.cpp:770]: Ha! I must be dyslexic

**Review by sjanzou — APPROVED** [review]
Thanks for removing commented and superfluous lines. The financial tests are all still passing - I restarted the failing mac pull action
